language: python
dist: bionic
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"
matrix:
  include:
    - os: osx
      language: generic
      python: "3"
      # Perform the manual steps on osx to install python2 and activate venv
      before_install:
        - brew update
        - brew unlink python@2
        - brew upgrade python3
        - python3 -m pip install virtualenv
        - virtualenv .venv -p python3
        - source .venv/bin/activate
      script:
        - CFLAGS="-Wall -Wextra -Wno-unused-parameter -isysroot $(xcrun --show-sdk-path)" ARCHFLAGS="-isysroot $(xcrun --show-sdk-path)"  python setup.py build
        - python -W default setup.py test
        - python benchmark.py
    - os: windows
      language: sh
      python: "3"
      before_install:
        - choco install python3
        - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
script:
    - CFLAGS="-Wall -Wextra -Wno-unused-parameter" python setup.py build
    - python -W default setup.py test
    - python benchmark.py
