dist: xenial
sudo: false
language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"
matrix:
  include:
    - os: osx
      language: sh
      python: "2.7"
      # Perform the manual steps on osx to install python2 and activate venv
      before_install:
        - brew update
        - brew upgrade python2
        - python2 -m pip install virtualenv
        - virtualenv .venv -p python2
        - source .venv/bin/activate
    - os: windows
      language: sh
      python: "3.8"
      before_install:
        - choco install python3
        - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
script:
    - CFLAGS="-Wall -Wextra -Wno-unused-parameter" python setup.py build
    - python -W default setup.py test
    - python benchmark.py
