language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
sudo: false
script:
    - python setup.py build_ext -i
    - python -m compileall -f .
    - python setup.py test
    - python benchmark.py
