dist: xenial
sudo: false
language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
matrix:
  include:
    - os: osx
      language: generic
script:
    - CFLAGS="-Wall -Wextra -Wno-unused-parameter" python setup.py build
    - python setup.py test
    - python benchmark.py
