version: "{build}"

clone_depth: 100

environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python33"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  # We need wheel installed to build wheels
  - "python.exe -m pip install wheel"

build_script:
  # Build the compiled extension
  - "python setup.py build"

test_script:
  # Run the project tests
- "python setup.py test"
- "python benchmark.py"

after_test:
  - "python.exe setup.py bdist_wheel"

artifacts:
  # bdist_wheel puts your built wheel in the dist directory
  - path: dist\*
